# Generated by Django 4.0.5 on 2022-06-03 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import jonse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("deleted_on", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default=jonse.models.default_listing_name,
                        max_length=200,
                        verbose_name="Name",
                    ),
                ),
                (
                    "jonse_amount",
                    models.BigIntegerField(default=0, verbose_name="Jonse"),
                ),
                (
                    "wolse_amount",
                    models.BigIntegerField(default=0, verbose_name="Wolse"),
                ),
                (
                    "wolse_rent",
                    models.IntegerField(default=0, verbose_name="Wolse rent"),
                ),
                (
                    "gwanlibi",
                    models.IntegerField(default=0, verbose_name="Management fees"),
                ),
                (
                    "jonse_interest_rate",
                    models.FloatField(
                        default=4, verbose_name="Jonse loan interest rate"
                    ),
                ),
                (
                    "jonse_interest_amount_per_month",
                    models.IntegerField(
                        default=0, verbose_name="Jonse loan monthly payment amount"
                    ),
                ),
                (
                    "monthly_expense",
                    models.IntegerField(default=0, verbose_name="Monthly expenses"),
                ),
                (
                    "number_of_rooms",
                    models.SmallIntegerField(default=1, verbose_name="# of rooms"),
                ),
                (
                    "number_of_bathrooms",
                    models.SmallIntegerField(default=1, verbose_name="# of bathrooms"),
                ),
                (
                    "condition",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "OK"), (2, "Old")],
                        default=1,
                        verbose_name="Condition",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
