# Generated by Django 4.0.4 on 2022-05-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("jonse_amount", models.IntegerField(default=0)),
                ("wolse_amount", models.IntegerField(default=0)),
                ("monthly_rent", models.IntegerField(default=0)),
                ("kollibi", models.IntegerField(default=0)),
            ],
        ),
    ]
