services:
    web:
        build: ./
        #entrypoint: python3 
        #command: manage.py runserver 0.0.0.0:8000
        env_file: .env
        volumes:
            - ./:/app
        ports:
            - 8001:8000
