services:

    nginx:
        image: nginx:alpine
        restart: on-failure:3
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - staticfiles:/var/www/staticfiles
        ports:
            - 80:80

    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db:/var/lib/postgresql/data

    web:
        build: ./
        command: gunicorn -b 0.0.0.0:8000 --workers 3 settings.wsgi:application
        restart: on-failure:3
        env_file: .env
        volumes:
            - staticfiles:/usr/src/code/staticfiles
        ports:
            - 8000

volumes:
    staticfiles:
    db:
