version: "3"

services:

    web:
        build: ./
        command: gunicorn -b 0.0.0.0:8000 --workers 3 settings.wsgi:application
        restart: always
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            DJANGO_DEBUG: ${DJANGO_DEBUG}
            DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        ports:
            - 80:8000
