version: "3"

services:

    web:
        build: ./
        command: python3 manage.py runserver 0.0.0.0:8000 --verbosity 1
        env_file: .env
        ports:
            - 80:8000
        volumes:
            - ./:/usr/src/code
