services:

    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/var/www/staticfiles
        ports:
            - 80:80

    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        

    web:
        build: ./
        command: python3 manage.py runserver 0.0.0.0:8000
        env_file: .env
        volumes:
            - ./:/usr/src/code
        ports:
            - 8000

