version: "3"

services:

    web:
        build: ./
        command: gunicorn -b 0.0.0.0:8000 --workers 3 settings.wsgi:application
        restart: always
        env_file: .env
        ports:
            - 80:8000
