version: "3"

services:

    web:
        build: ./
        command: gunicorn -b 0.0.0.0:8000 --workers 3 settings.wsgi:application
        restart: on-failure:3
        env_file: .env
        volumes:
            - staticfiles:/usr/src/code/staticfiles
        ports:
            - 8000

    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - staticfiles:/var/www/staticfiles
        ports:
            - 80:80

volumes:
    staticfiles: